version: '3.8'

services:
  voting-app:
    build: ./
    command: ./wait-for-postgres.sh db ./voting-app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: unless-stopped
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432
